using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text.Json;
using atp_enterprise_app_wpf.Models;

namespace atp_enterprise_app_wpf.Services
{
    public class ProcedureLoaderService
    {
        private readonly string _storageDir;
        private static ProcedureLoaderService? _instance;
        public static ProcedureLoaderService Instance => _instance ??= new ProcedureLoaderService();

        private ProcedureLoaderService()
        {
            string appData = Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData);
            _storageDir = Path.Combine(appData, "ATP_Enterprise", "Procedures");
            if (!Directory.Exists(_storageDir))
            {
                Directory.CreateDirectory(_storageDir);
                // Create a default procedure if none exist
                SaveProcedure(CreateDefaultProcedure());
            }
        }

        public List<AtpProcedure> ListProcedures()
        {
            var procedures = new List<AtpProcedure>();
            try
            {
                var files = Directory.GetFiles(_storageDir, "*.json");
                foreach (var file in files)
                {
                    try
                    {
                        var json = File.ReadAllText(file);
                        var proc = JsonSerializer.Deserialize<AtpProcedure>(json);
                        if (proc != null) procedures.Add(proc);
                    }
                    catch (Exception) { /* Ignore corrupted files */ }
                }
            }
            catch (Exception ex)
            {
                System.Diagnostics.Debug.WriteLine($"Failed to list procedures: {ex.Message}");
            }
            return procedures.OrderByDescending(p => p.IssueDate).ToList();
        }

        public void SaveProcedure(AtpProcedure procedure)
        {
            procedure.IssueDate = DateTime.Now;
            string file = Path.Combine(_storageDir, $"{procedure.ProcedureId}.json");
            var options = new JsonSerializerOptions { WriteIndented = true };
            string json = JsonSerializer.Serialize(procedure, options);
            File.WriteAllText(file, json);
        }

        public AtpProcedure? LoadProcedure(string id)
        {
            string file = Path.Combine(_storageDir, $"{id}.json");
            if (!File.Exists(file)) return null;
            var json = File.ReadAllText(file);
            return JsonSerializer.Deserialize<AtpProcedure>(json);
        }

        public void DeleteProcedure(string id)
        {
            string file = Path.Combine(_storageDir, $"{id}.json");
            if (File.Exists(file)) File.Delete(file);
        }

        private AtpProcedure CreateDefaultProcedure()
        {
            return new AtpProcedure
            {
                ProcedureTitle = "Default Global ATP Specification",
                ProductFamily = "All Products",
                Revision = "1.0.0",
                Author = "System",
                ChangeSummary = "Autogenerated fallback procedure.",
                TestSequence = new List<TestDefinition>
                {
                    new() { TestId = "PWR_001", Name = "AC Power Source Verification", Category = "Power", Description = "Verify AC power line is connected and stable.", ExpectedSpecification = "AC Online", TimeoutMs = 10000, IsMandatory = true },
                    new() { TestId = "BOOT_001", Name = "System Boot Verification", Category = "System", Description = "Verify system has booted successfully with positive uptime.", ExpectedSpecification = "Uptime > 0s", TimeoutMs = 10000, Prerequisites = new() { "PWR_001" }, IsMandatory = true },
                    new() { TestId = "CPU_001", Name = "Processor Identification", Category = "Processor", Description = "Verify CPU model and core count match expected configuration.", ExpectedSpecification = "CPU Detected", TimeoutMs = 15000, Prerequisites = new() { "BOOT_001" } },
                    new() { TestId = "RAM_001", Name = "Memory Capacity Verification", Category = "Memory", Description = "Verify installed RAM capacity meets minimum specification.", ExpectedSpecification = "RAM >= 4 GB", MinimumNumericValue = 4.0, TimeoutMs = 15000, Prerequisites = new() { "BOOT_001" } },
                    new() { TestId = "STG_001", Name = "Storage Device Detection", Category = "Storage", Description = "Verify primary storage device is detected and accessible.", ExpectedSpecification = "Drive Detected", TimeoutMs = 20000, Prerequisites = new() { "BOOT_001" } },
                    new() { TestId = "STG_002", Name = "Storage Read Performance", Category = "Storage", Description = "Measure sequential read throughput of primary storage device.", ExpectedSpecification = "Read > 50 MB/s", MinimumNumericValue = 50.0, TimeoutMs = 60000, Prerequisites = new() { "STG_001" } },
                    new() { TestId = "NET_001", Name = "Ethernet Link Verification", Category = "Network", Description = "Verify Ethernet link state is UP.", ExpectedSpecification = "Link UP", TimeoutMs = 15000, Prerequisites = new() { "BOOT_001" } },
                    new() { TestId = "NET_002", Name = "Network Throughput", Category = "Network", Description = "Measure loopback or local network throughput.", ExpectedSpecification = "Throughput > 100 Mbps", MinimumNumericValue = 100.0, TimeoutMs = 60000, Prerequisites = new() { "NET_001" } }
                }
            };
        }
    }
}
